- debug: msg="{{ deploy_region_id }}"
- debug: msg="{{ deploy_size }}"
- debug: msg="{{ image_id }}"

# Create a new Droplet
# Will return the droplet details including the droplet id (used for idempotence)
- name: deploy droplet
  digital_ocean: >
      state=present
      command=droplet
      name="demo"
      api_token="{{ api_token }}"
      size_id={{ deploy_size }}
      region_id={{ deploy_region_id }}
      image_id={{ image_id }}
      wait_timeout=500
  register: my_droplet

- debug: msg="ID is {{ my_droplet.droplet.id }}"
- debug: msg="IP is {{ my_droplet.droplet.ip_address }}"
